# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded EspAnalizoj 0.993 [list source [file join $dir EspAnalizoj.xotcl]]
package ifneeded EspBazaLingvo 0.993 [list source [file join $dir EspBazaLingvo.xotcl]]
package ifneeded EspDeTradukilo 0.993 [list source [file join $dir EspDeTradukilo.xotcl]]
package ifneeded EspEnSintaksaAnalizo 0.993 [list source [file join $dir EspEnSintaksaAnalizo.xotcl]]
package ifneeded EspEnTradukilo 0.993 [list source [file join $dir EspEnTradukilo.xotcl]]
package ifneeded EspHTTPServilo 0.993 [list source [file join $dir EspHTTPServilo.xotcl]]
package ifneeded EspParalelTekstaro 0.993 [list source [file join $dir EspParalelTekstaro.xotcl]]
package ifneeded EspPlSintaksaAnalizo 0.993 [list source [file join $dir EspPlSintaksaAnalizo.xotcl]]
package ifneeded EspPlTradukilo 0.993 [list source [file join $dir EspPlTradukilo.xotcl]]
package ifneeded EspRevoMontrilo 0.993 [list source [file join $dir EspRevoMontrilo.xotcl]]
package ifneeded EspRuTradukilo 0.1 [list source [file join $dir EspRuTradukilo.xotcl]]
package ifneeded EspSintaksaAnalizo 0.993 [list source [file join $dir EspSintaksaAnalizo.xotcl]]
package ifneeded EspSvTradukilo 0.993 [list source [file join $dir EspSvTradukilo.xotcl]]
package ifneeded EspTMServilo 0.993 [list source [file join $dir EspTMServilo.xotcl]]
package ifneeded EspTeknikajIloj 0.993 [list source [file join $dir EspTeknikajIloj.xotcl]]
package ifneeded EspTradukGUI 0.993 [list source [file join $dir EspTradukGUI.xotcl]]
package ifneeded EspTradukaVortaro 0.993 [list source [file join $dir EspTradukaVortaro.xotcl]]
package ifneeded EspTradukaVortaroGUI 0.993 [list source [file join $dir EspTradukaVortaroGUI.xotcl]]
package ifneeded EspTradukadoBazo 0.993 [list source [file join $dir EspTradukadoBazo.xotcl]]
package ifneeded EspTradukilo 0.993 [list source [file join $dir EspTradukilo.xotcl]]
package ifneeded EsperantiloProgramado 0.993 [list source [file join $dir EsperantiloProgramado.xotcl]]
package ifneeded EsperantoEdit 0.993 [list source [file join $dir EsperantoEdit.xotcl]]
package ifneeded IDEBaseGUI 0.84 [list source [file join $dir IDEBaseGUI.xotcl]]
package ifneeded can2svg 0.1 [list source [file join $dir can2svg.xotcl]]
package ifneeded xdobry::sql 0.78 [list source [file join $dir xdobry_sql.xotcl]]
package ifneeded xdobry::sqlite 0.77 [list source [file join $dir xdobry_sqlite.xotcl]]
